sudo: true
language: node_js
compiler: g++

node_js:
  - "5"
  - "4"
  - "0.12"


before_install:
  - sudo apt-get update -qq
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test

install:
  - sudo apt-get install -y libavahi-compat-libdnssd-dev g++-4.8
  - export CXX="g++-4.8"
